"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api";
type User = { name: string; email: string; role: "customer" | "admin" };
type Quote = { _id: string; service: string; message: string; status: string; createdAt: string };
export default function ProfilPage() {
  const [user, setUser] = useState<User | null>(null); const [quotes, setQuotes] = useState<Quote[]>([]); const [state, setState] = useState<"loading" | "ready" | "signedOut" | "error">("loading");
  useEffect(() => { void Promise.resolve().then(async () => { const token = localStorage.getItem("tvojaFirmaToken"); if (!token) { setState("signedOut"); return; } const headers = { Authorization: `Bearer ${token}` }; const [userResponse, quotesResponse] = await Promise.all([fetch(`${apiUrl}/auth/me`, { headers }), fetch(`${apiUrl}/quotes/mine`, { headers })]); if (userResponse.status === 401 || quotesResponse.status === 401) { setState("signedOut"); return; } if (!userResponse.ok || !quotesResponse.ok) throw new Error(); const userData = await userResponse.json(); const quotesData = await quotesResponse.json(); setUser(userData.user); setQuotes(quotesData.quotes); setState("ready"); }).catch(() => setState("error")); }, []);
  if (state === "loading") return <div className="p-16 text-center text-slate-600">Učitavanje profila...</div>;
  if (state === "signedOut") return <div className="min-h-[calc(100vh-70px)] bg-stone-50 p-16 text-center"><h1 className="text-3xl font-semibold">Niste prijavljeni</h1><Link href="/prijava" className="mt-6 inline-block rounded-full bg-slate-900 px-5 py-3 font-semibold text-white">Prijavite se</Link></div>;
  if (state === "error" || !user) return <div className="p-16 text-center text-red-700">Profil trenutno nije dostupan. Pokušajte ponovo kasnije.</div>;
  return <div className="min-h-[calc(100vh-70px)] bg-stone-50 px-6 py-14"><div className="mx-auto max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-orange-700">Moj nalog</p><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-semibold text-slate-900">Zdravo, {user.name.split(" ")[0]}.</h1><p className="mt-2 text-slate-600">{user.email}</p></div><Link href="/kontakt" className="rounded-full bg-slate-900 px-5 py-3 font-semibold text-white">Novi upit</Link></div><section className="mt-12"><h2 className="text-2xl font-semibold text-slate-900">Moji upiti</h2>{quotes.length === 0 ? <div className="mt-5 rounded-2xl bg-white p-7 text-slate-600 ring-1 ring-slate-200">Još nemate upita povezanih sa ovim nalogom. <Link href="/kontakt" className="font-semibold text-orange-700">Pošaljite prvi upit.</Link></div> : <div className="mt-5 grid gap-4">{quotes.map((quote) => <article key={quote._id} className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold text-slate-900">{quote.service}</h3><span className="rounded-full bg-orange-50 px-3 py-1 text-xs font-semibold text-orange-800">{quote.status}</span></div><p className="mt-3 text-slate-600">{quote.message}</p><p className="mt-4 text-xs text-slate-400">{new Date(quote.createdAt).toLocaleString("sr-RS")}</p></article>)}</div>}</section></div></div>;
}
